[[ssh_keys]]
label = "Work (GitHub)"
path = "/home/user/.ssh/id_ed25519_work"
default = true

[[ssh_keys]]
label = "Personal (GitHub)"
path = "/home/user/.ssh/id_ed25519_personal"
default = false

[[ssh_keys]]
label = "Customer Project (GitLab)"
path = "/home/user/.ssh/id_rsa_customer"
default = false


[[git_users]]
label = "Work"
name = "Taro Yamada"
email = "taro.yamada@company.example"
default = true
default_repositories = [
  "git@github.com:company/example-repo.git",
  "https://github.com/company/another-repo",
]

[[git_users]]
label = "Personal"
name = "Taro Yamada"
email = "taro.yamada@example.mail.com"
default = false
default_repositories = ["git@github.com:taro/personal-repo.git"]

[[git_users]]
label = "Customer (Contract)"
name = "Taro Yamada"
email = "taro.yamada@customer.example"
default = false
default_repositories = ["git@gitlab.example.com:customer/project.git"]
